# Generated by Django 4.2.9 on 2024-01-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="archivo/")),
            ],
        ),
        migrations.CreateModel(
            name="venture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("venture_id", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("path", models.FilePathField()),
                ("prompt_template", models.TextField()),
            ],
        ),
    ]
